### ISSUE TITLE
hpi package generation issue

### ISSUE THREAD

**Issue by SamratDawn** [jenkinsci/login-theme-plugin#123]
### Jenkins and plugins versions report

<details>
  <summary>BUILD FAILURE during hpi generation</summary>

  
Environment- Windows
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

1. Clone the repo
2. Run the command "mvn clean hpi:hpi"

### Expected Results

BUILD SUCCESS

### Actual Results

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2024-10-22T17:28:49+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.57:hpi (default-cli) on project login-theme: Missing C:\Users\SAMRAT DAWN\Desktop\login-theme-plugin-main\target\classes\index.jelly. Delete any <description> from pom.xml and create src/main/resources/index.jelly:
[ERROR] <?jelly escape-by-default='true'?>
[ERROR] <div>
[ERROR]     The description here?
[ERROR] </div>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### Anything else?

The index.jelly file exists still I am getting this issue.

**Comment by jonesbusy** [comment]
This is specific to your environment 

The main branch build on both Linux and Windows https://ci.jenkins.io/job/Plugins/job/login-theme-plugin/job/main/
