### ISSUE TITLE
Support for branding

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/login-theme-plugin#33]
### What feature do you want to see added?

Add branding support in addition of the already implemented header, head and footer.

Example in https://github.com/jenkinsci/design-library-plugin/pull/277

CSS should be pretty straightforward to change, but need to consider the logo/svg branding

### Upstream changes

https://github.com/jenkinsci/jenkins/pull/8462

**Comment by harshhgithub** [comment]
Hey , i am not understanding this issue . Pls help ,i want to contribute

**Comment by sridamul** [comment]
Hey @jonesbusy, How do you test the login page when you run using `mvn hpi:run` ? cause I can't find a way to logout or login

**Comment by sridamul** [comment]
I have added a new text-box which fetches the url and pass it to the img-src of simple-branding.jelly file, but I couldn't test the changes cause I can't find any option to view the login page

![branding](https://github.com/jenkinsci/login-theme-plugin/assets/107404972/b535493d-6e95-43a9-b4c0-60ca9e6127db)

**Comment by jonesbusy** [comment]
You can run hpi:run and create a fake local user on the system config. Then you will be able to login/logout
