### ISSUE TITLE
Missing test coverage

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/login-theme-plugin#34]
### What feature do you want to see added?

This plugin miss some essential testing to validate non-regression

- Minimalist unit for the `SimplePageDecorator`
- HTMLUnit for UI configuration
- ~Jenkins Configuration Test~

More information on https://www.jenkins.io/doc/developer/testing/

**Comment by Freedisch** [comment]
@jonesbusy , I would like to work on this 👀

**Comment by jonesbusy** [comment]
@Freedisch Feel free to submit a PR

**Comment by ramlakshman2233** [comment]
Can I do this job

**Comment by sridamul** [comment]
Hey @jonesbusy I am completely new to write tests but eager to learn. 

> Minimalist unit for the SimplePageDecorator

From my understanding do you mean to write a test for https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/SimplePageDecorator.java?

**Comment by jonesbusy** [comment]
You can check jacoco coverage using `mvn -Penable-jacoco clean install` on the target/site folder. Check the code that is not cover edand write test for it.

Don't expect maintainers to tell you exactly what and how to do it. It's part of the research. You can explore https://www.jenkins.io/doc/developer/testing/ or even check other plugin to see how tests are and can be implemented

This plugin is missing some test coverage, any PR that increase the coverage is good to take 

Regards,

**Comment by sridamul** [comment]
> You can check jacoco coverage using mvn -Penable-jacoco clean install on the target/site folder. Check the code that is not cover edand write test for it.

Sure. I will do it

> Don't expect maintainers to tell you exactly what and how to do it. It's part of the research.

Sorry for the inconvenience. But I think you misunderstood my comment, I am trying to clarify my misconception about the scope of the issue. Not really seeking the direct implementation part. Once again feeling sorry If I had made you inconvenient.
